spring.application.name=course-api

spring.datasource.url=jdbc:postgresql://localhost:5432/academy_cipp
spring.datasource.username=postgres
spring.datasource.password=ivanpardo


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.port=8080